apiVersion: batch/v1
kind: Job
metadata:
  name: before
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    # argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: main
        image: sikalabs/slu:v0.89.0
        command:
          - /bin/bash
          - -c
          - slu ondrejsika dogsay "PreSync hook"
      restartPolicy: Never
  backoffLimit: 0
