apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: main
        image: sikalabs/dogsay:v0.1.0
        command:
          - /bin/bash
          - -c
          - dogsay "Done, Good Job!"
      restartPolicy: Never
  backoffLimit: 0
