apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  destination:
    namespace: rabbitmq
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 10.2.1
    helm:
      releaseName: rabbitmq
      values: |
        auth:
          username: admin
          password: admin
        replicaCount: 3
        ingress:
          enabled: true
          path: /
          hostname: rabbitmq.k8s.sikademo.com
          tls: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
