apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-helm
  namespace: argocd
spec:
  destination:
    namespace: hello-world-helm
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.sikalabs.io
    chart: hello-world
    targetRevision: 0.3.0
    helm:
      releaseName: hello-world
      values: |
        replicas: 4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
