# https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml
# https://artifacthub.io/packages/helm/argo/argo-cd?modal=values
server:
  ingress:
    enabled: true
    hostname: argocd.k8s.sikademo.com
    tls: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
configs:
  secret:
    argocdServerAdminPassword: $2a$10$od0Ap6gZohcqAK5WInvdv.ykbU5asPfIbwFRzn/upGIT6VGRrbAdO # password is: admin
