# https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml
# https://artifacthub.io/packages/helm/argo/argo-cd?modal=values
configs:
  cm:
    url: https://argocd.k8s.sikademo.com
    exec.enabled: true
    oidc.config: |
      name: SSO
      issuer: https://sso.sikademo.com/realms/sikademo
      clientID: argocd
      clientSecret: argocd
      requestedScopes: ["openid", "profile", "email", "groups"]
      logoutURL: "https://sso.sikademo.com/realms/sikademo/protocol/openid-connect/logout?client_id=argocd&id_token_hint={{token}}&post_logout_redirect_uri=https://argocd.k8s.sikademo.com"
    oidc.tls.insecure.skip.verify: "true"

  rbac:
    policy.csv: |
      g, argocd-admin, role:admin
      g, argocd-readonly, role:readonly

      g, argocd-foo, role:foo

      p, role:foo, projects, get, foo/*, allow
      p, role:foo, applications, get, foo/*, allow

      p, role:foo, Pod, delete, foo/*, allow
      p, role:foo, exec, create, foo/*, allow
