apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-hooks
  namespace: argocd
spec:
  destination:
    namespace: sync-hooks
    server: https://kubernetes.default.svc
  project: default
  source:
    path: sync-hooks
    repoURL: https://github.com/argocd-training/examples.git
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
