apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world-helm-git
  namespace: argocd
spec:
  destination:
    namespace: hello-world-helm-git
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://gitlab.sikademo.com/ondrejsika/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: hello
      values: |
        replicas: 4
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
