{{ range $suffix := .Values.suffixes }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbb-{{ $suffix }}
spec:
  revisionHistoryLimit: 0
  replicas: 3
  selector:
    matchLabels:
      app: bbb-{{ $suffix }}
  template:
    metadata:
      labels:
        app: bbb-{{ $suffix }}
    spec:
      containers:
        - name: main
          image: sikalabs/hello-world-server
          ports:
            - name: http
              containerPort: 8000
          resources:
            requests:
              cpu: 20m
              memory: 20Mi
            limits:
              cpu: 40m
              memory: 40Mi
{{ end }}
