apiVersion: batch/v1
kind: Job
metadata:
  name: after
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: main
        image: sikalabs/slu:v0.39.0
        command:
          - /bin/bash
          - -c
          - slu mail send -H maildev.sikademo.com -P 25 -f example@example.com -t example@sikademo.com -s "Post Sync Hook" -m "Hello from Post Sync Hook"
      restartPolicy: Never
  backoffLimit: 0
