apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iceland-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: iceland-1
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/sikalabs/charts.git
      path: charts/one-image
      helm:
        valueFiles:
        - $values/examples/multiple_sources/apps/iceland_1/values.yml
    - repoURL: https://github.com/ondrejsika/argocd-training.git
      ref: values
