apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manifests
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    path: examples/manifests
    repoURL: https://gitlab.sikademo.com/ondrejsika/argocd-training.git
